### ISSUE TITLE
Can you upload the page in the form of XAML?

### ISSUE THREAD

**Issue by AbhishekHumagain** [act70255/ListViewSwipeGesture#2]
The view is in the form of .cs only so it would be easier to modify the .XAML file so, can you please upload it?

**Comment by act70255** [comment]
Sure, It’s may take few days

**Comment by AbhishekHumagain** [comment]
Thank you.

**Comment by act70255** [comment]
Hi, I upload PageXaml.xaml & PageXaml.xaml.cs
Please modify to "MainPage = new Pages.PageXaml();" in App.cs to run it

If you need more complicated template structure, Please try sflistview by syncfusion
